import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import "@/styles/custom-tailwindcss.css";

// import { SessionProvider } from "next-auth/react";
import ReactQueryProviders from "@/providers/react-query";
import ThemeProvider from "@/providers/theme";
import LayoutProvider from "@/providers/layout";
import DeviceContext from "@/providers/device-context";
import { Toaster } from "@/components/ui/sonner";

const geistRem = localFont({
  src: "../public/fonts/REM-VariableFont_wght.ttf",
});
const geistRemItalic = localFont({
  src: "../public/fonts/REM-Italic-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
  title: "hanoi coffee",
  description: "Generated by create next app",
  // viewport: {
  //   width: "device-width",
  //   initialScale: 1.0,
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistRem.className} ${geistRemItalic.className} font-sans`}
      >
        <ReactQueryProviders>
          <ThemeProvider>
            <DeviceContext>
              {/* <SessionProvider> */}
              <LayoutProvider>
                {children}
                <Toaster />
              </LayoutProvider>
              {/* </SessionProvider> */}
            </DeviceContext>
          </ThemeProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
