import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
// import { SessionProvider } from "next-auth/react";
import ReactQueryProviders from "@/providers/react-query";
import ThemeProvider from "@/providers/theme";
import LayoutProvider from "@/providers/layout";
import DeviceContext from "@/providers/device-context";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "hanoi coffee",
  description: "Generated by create next app",
  // viewport: {
  //   width: "device-width",
  //   initialScale: 1.0,
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProviders>
          <ThemeProvider>
            <DeviceContext>
              {/* <SessionProvider> */}
              <LayoutProvider>
                {children}

                <Toaster />
              </LayoutProvider>
              {/* </SessionProvider> */}
            </DeviceContext>
          </ThemeProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
